### ISSUE TITLE
Implement Android Keep Screen On

### ISSUE THREAD

**Issue by Lingomat** [aikuma/aikuma#264]
It is highly desirable for Aikuma to keep the screen on when recording. If the phone goes to sleep, the recording is terminated. This means the recording can only go for as long as the display timeout as set in Android's settings. Stock Android 4.4.3, this can only be set to 30 minutes. This means on a Nexus 5, for instance, you cannot record longer than 30 minutes.

Recently I failed to set this value when I switched phones out with a new Aikuma build. While this is obviously my fault, the result was a number of botched recording events as the phone went to sleep. It turns out to be entirely unnecessary.

The fix is as easy as setting android:keepScreenOn="true" in the activity <RelativeLayout> tag. https://developer.android.com/training/scheduling/wakelock.html

(I don't think wake-locks are necessary, we are not doing work in the background with the phone in sleep mode, right?)

Can this please be elevated to important. It's a showstopper.

**Comment by stevenbird** [comment]
Aikuma should not sleep during playback either. Right now, the screen timeout causes playback to stop, and when you turn the screen on, playback is reset to the start of the audio.
