### ISSUE TITLE
Metadata json format

### ISSUE THREAD

**Issue by hleeldc** [aikuma/aikuma#345]
I would like to point out a couple of minor issues with metadata json files. The following illustrates a metadata json file of a respeaking audio.

```
Format:         "vnd.wav"
location:       "null"         
androidID:      "a8cd8b5899a6bc6"
speakers:       ["METETDZCZALU"],
date:           "2014-11-10T02:18:40Z"          
suffix:         "817610"       
file_type:      "respeaking"
version:        "v01"          
sampleRate:     16000          
languages:      [{code:"aau", name:"Abau"}]     
source:         "v01-eqpmjpanniui-hlee.test.ldc@gmail.com-source"
BitsPerSample:  16             
item_id:        "eqpmjpanniui" 
name:           ""             
NumChannels:    1              
user_id:        "hlee.test.ldc@gmail.com"       
durationMsec:   4605           
```

#### Field name inconsistency

There are 3 ways of naming fields. Can we pick one?

  - UpperCamelCase, e.g. BitsPerSample, NumChannels
  - lowerCamelCase, e.g. androidID, sampleRate
  - snake_case, e.g. file_type, user_id

#### Source reference

The source field references a source recording. The value consists of 4 parts. 

  - directory structure version: v01
  - item id: eqpmjpanniui
  - user id: hlee.test.ldc@gmail.com
  - file type: source

I think only 2 parts are necessary and the rest is redundant. And, I think it's better to make it an object, e.g.

```
source:         {version: "v01", user_id: "hlee.test.ldc@gmail.com"}
```

**Comment by stevenbird** [comment]
We've agreed to use snake_case. I'm happy to retain the partly-redundant source attribute.

**Comment by stevenbird** [comment]
@lisaslyis please make these changes for all of our JSON files (e.g. speaker metadata) and update the [metadata documentation](https://github.com/aikuma/aikuma/wiki/Metadata), modifying the existing information and adding sections for each other JSON file type.

**Comment by lisaslyis** [comment]
@stevenbird Yes, All JSON files used in Aikuma will be changed to use a snake_case convention.
