### ISSUE TITLE
languages field in metadata json

### ISSUE THREAD

**Issue by hleeldc** [aikuma/aikuma#365]
Spun off from issue #349.

Currently, the languages field look something like this. Note that it stores language names too.

    "languages":[{"name":"Abu' Arapesh","code":"aah"}]

@stevenbird said that
> ... There's no need for this predictable information. We already store the language-code to language mapping. So it can be "languages": "abc jkl xyz"

and that

> We can store the language codes table, available from http://www-01.sil.org/iso639-3/download.asp

**Comment by stevenbird** [comment]
Duplicate of #189, resolved in #417
