### ISSUE TITLE
Bounce emails

### ISSUE THREAD

**Issue by stevenbird** [aikuma/aikuma#408]
When a file is shared with the lp20.org account, an email notification is also sent, and this bounces because the email account doesn't seem to exist:

```Delivery to the following recipient failed permanently: lp20.org@gmail.com```

It would probably be better for sharing not to give any email notification.

**Comment by stevenbird** [comment]
I think this is in the cloud library. There should be an option in the API call that allows sharing to happen without email notification.

**Comment by HedvigS** [comment]
Yesterday I created I started using Aikuma with my google drive. I recorded 3 files, and some respeak and interpretation. We also tried sharing peer-to-peer, I didn't receive any files but perhaps something went on there.

Today I've gotten 85+ messages of this type:

Delivery to the following recipient failed permanently:

     lp20.org@gmail.com

Technical details of permanent failure:
Message rejected.  See https://support.google.com/mail/answer/69585 for more information.

----- Original message -----

MIME-Version: 1.0
X-Received: by 10.66.66.66 with SMTP id d2mr2497369pat.5.1434486220285; Tue,
 16 Jun 2015 13:23:40 -0700 (PDT)
X-No-Auto-Attachment: 1
References: <84bf169b-6e91-40a9-b5ea-d5d5625c7314@docs-share.google.com>
Message-ID: <001a113628f49870470518a859cd@google.com>
Date: Tue, 16 Jun 2015 20:23:40 +0000
Subject: dcqajbtltiwq-hedvig.skirgard@gmail.com-source.wav
From: "hedvig.skirgard@gmail.com (via Google Drive)" <hedvig.skirgard@gmail.com>
To: lp20.org@gmail.com
Content-Type: multipart/alternative; boundary=001a113628f49870280518a859ca

I've shared an item with you:

dcqajbtltiwq-hedvig.skirgard@gmail.com-source.wav
http://drive.google.com/file/d/0B-lVFHmduY1WdDVlRXhUT1c1cW8/view?usp=sharing

It's not an attachment -- it's stored online. To open this item, just click
the link above

**Comment by stevenbird** [comment]
The bounce message is generated when a file is shared with the lp20.org account. I am able to send an email from my gmail account to lp20.org, but I am not able to share a file via Aikuma with lp20.org without getting a bounce message. @lisaslyis would you please see if there's a way to turn off the sending of an email when a file is shared via Google Drive?

**Comment by stevenbird** [comment]
Now that we've changed the sharing mechanism, this problem seems to have gone away.
