### ISSUE TITLE
Speaker screen

### ISSUE THREAD

**Issue by stevenbird** [aikuma/aikuma#409]
The person icon takes us to a screen that lists speakers. It should be possible to select a speaker in order to see a list of the speaker's activity (the file-list, filtered by speaker, displayed in time order)

**Comment by Lingomat** [comment]
Can we have files that are in some way attached to a speaker rather than an activity? I'm thinking of consent and metadata.

**Comment by stevenbird** [comment]
@Lingomat we already store speaker metadata (the languages they speak). If there's a proposal to add extra metadata we can consider this (via a separate issue).

**Comment by Lingomat** [comment]
I was really thinking about audio or video files and where metadata is a speaker bio, basically. I think there's may be a better way to do what I want, we'll discuss.

**Comment by stevenbird** [comment]
If the speaker is tagged in an item (containing a speaker bio or informed consent statement), then the item will show up as one of the speaker's activities. We can add hash tags when necessary to distinguish special kinds of item.

**Comment by stevenbird** [comment]
Pressing the back button takes the user back to the main activity.
