### ISSUE TITLE
Orientation crash

### ISSUE THREAD

**Issue by Lingomat** [aikuma/aikuma#418]
I'm still getting crashes on change of orientation, on the Google Play build, 0.8.4.

This is reproducible as follows: Make new recording -> review -> name recording -> add user -> select user/lang -> now change phone orientation and Aikuma crashes every time on a Nexus 5.

**Comment by lisaslyis** [comment]
@Lingomat  Thanks for a feedback. I could reproduce the same bug and found another one.
Make new speaker -> name speaker -> select lang -> now the orientation change disables the confirmation button even though languages are selected.
I'm gonna fix these two bugs in the next PR.
