### ISSUE TITLE
Unable to take photo with rear-facing camera

### ISSUE THREAD

**Issue by Lingomat** [aikuma/aikuma#423]
When adding a user, if using the rear facing camera in landscape mode, Aikuma reports that the file was unable to be saved when returning from having taken a photo with the stock Android 5 camera app on a Nexus 5.

Unclear if this is size related or aspect ratio, e.g. if it would have worked in portrait.

**Comment by Lingomat** [comment]
Hmm, a couple of days ago this was happening every time and now I can't reproduce it!

**Comment by floere** [comment]
A perfect example of a Heisenbug :smile:

**Comment by Lingomat** [comment]
Hah, quite so!

**Comment by lisaslyis** [comment]
I think this was related to the bug I mentioned in #418. (orientation in speaker-creation activity)
This was resolved by the commit d09533c4
