### ISSUE TITLE
Flat file structure in Google Drive

### ISSUE THREAD

**Issue by stevenbird** [aikuma/aikuma#427]
Revert to the flat file structure in Google Drive, to avoid the problem with idiosyncratic file attributes that prevented files from being shared (and required copying). Filenames will contain the full pathname from the [file structure](https://github.com/aikuma/aikuma/wiki/File-Storage).

They will land in the `incoming` directory and will be found efficiently using a filename glob or file attribute, then be moved to the root `/aikuma` directory.

**Comment by stevenbird** [comment]
The proposal to support multiple projects (where the Aikuma client knew the name of the root directory, e.g. `/aikuma2`) might not be possible to implement, since we won't know which project to copy an incoming file to. Files are shared with users, not users' projects.

**Comment by hleeldc** [comment]
It depends on what "project" means. The central storage doesn't make such distinction. But, it could be useful for users. For example, you could have two different collections that you want to organize in two different folders on your phone. This is a totally different story, but it's also possible that you can have multiple central storage servers each of which represent one project.

**Comment by stevenbird** [comment]
I think that the idea of having multiple projects is too challenging to implement well. E.g. what happens when you create a file on a phone and realise it was in the wrong project? I think we should try to implement projects using tags.

**Comment by Lingomat** [comment]
A project can be minimally the Google account used to log into the devices, right? 

I think my project-based thinking was all the result of thinking that somehow all possible Aikuma app instances would be uploading to the same 'place' but they presumably they aren't.

**Comment by stevenbird** [comment]
We still need to decide whether to proceed with this flat file structure.

**Comment by stevenbird** [comment]
Resolved in #491.
