### ISSUE TITLE
Building Aikuma

### ISSUE THREAD

**Issue by stevenbird** [aikuma/aikuma#429]
@lisaslyis would you please post your instructions for building Aikuma from the repository in a new [wiki](https://github.com/aikuma/aikuma/wiki) page, so that @Lingomat and I can easily build it from Android Studio.

**Comment by lisaslyis** [comment]
@stevenbird I've made new instructions in the front page of aikuma repository. Do you want me to move this into wiki page?

**Comment by stevenbird** [comment]
@Lingomat would you please check you can build from [these instructions](https://github.com/aikuma/aikuma/blob/master/README.md), and post any questions here?

**Comment by Lingomat** [comment]
Righty, got as far as I can. The instructions don't really have a lot to do with Windows but I soldiered on. In the end I'm getting close but it blows out with a compiler error as below. This is all after building the cloud storage library and copying that into the project, and building "search-interface" branch. 

```-compile:
    [javac] Compiling 105 source files to C:\Users\Mat\Documents\GitHub\aikuma\A
ikuma\bin\classes
    [javac] C:\Users\Mat\Documents\GitHub\aikuma\Aikuma\src\org\lp20\aikuma\ui\M
enuBehaviour.java:149: error: cannot find symbol
    [javac]                             intent = new Intent(activity, TestActivity.class);
    [javac]                                                           ^
    [javac]   symbol:   class TestActivity
    [javac]   location: class MenuBehaviour
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 1 error
```

**Comment by Lingomat** [comment]
One oddity, the doc mentions 4.2.2 which is android-17. The build.properties file had android-16 so I changed it to 17.

**Comment by lisaslyis** [comment]
@Lingomat Could you comment out the lines (https://github.com/aikuma/aikuma/blob/search-interface/Aikuma/src/org/lp20/aikuma/ui/MenuBehaviour.java#L148:L151). I thought I've committed the corresponding files(TestAcitivity.java), but it seems missing.

**Comment by Lingomat** [comment]
Gets a lot further:

C:\Users\Mat\Documents\GitHub\aikuma\Aikuma>d:\tools\apache-ant-1.9.4\bin\ant ch
eckstyle clean debug install >builddump.txt

BUILD FAILED
D:\Android\tools\ant\build.xml:892: The following error occurred while executing
 this line:
D:\Android\tools\ant\build.xml:894: The following error occurred while executing
 this line:
D:\Android\tools\ant\build.xml:906: The following error occurred while executing
 this line:
D:\Android\tools\ant\build.xml:283: null returned: 2

Total time: 48 seconds

The output of the build process is here: https://gist.github.com/Lingomat/438393ebf25ce578d8ef

**Comment by lisaslyis** [comment]
@Lingomat Have you deleted the old version of aikuma-cloud-storage*.jar in the lib folder? The old library needs to be replaced by the new library. It seems like there are two duplicate libraries (aikuma-cloud-storage.jar and aikuma-cloud-storage-old.jar)

**Comment by Lingomat** [comment]
Yes! I replaced it but I didn't delete the old one, I renamed it. I assumed that files wouldn't be linked unless they were referenced in some build/header  file... d'oh.

I needed to delete version on the phone, (obviously can't update signed Play with debug version), manually adb installed the apk. Worked. Runs fine, woohoo! 

Hrm, now related to your instructions. I just used the Gradle that comes with Android Studio. The built Jar ended up in user folder .m2/ etc. I did have to install Ant (can't Gradle just be used for this?). Some environment variables were needed to make things work, Java_home, Android _Home etc. Took some time to figure out how to make the reference to Google Play Services lib work right, usual Windows/*nix path stuff.

Of course what I'd really like to do is just be able to import the lot into Android Studio and build it from there but one step at a time, so much more to learn...

**Comment by lisaslyis** [comment]
Ant is used to build Aikuma now, but Gradle can also be an alternative. The current Aikuma project can be built in Eclipse, which I've usually used for development and was the main IDE for Android. Because Google tries to spread Android Studio as the main IDE now, they say Android Studio project can be created by importing the Eclipse project. There are some [instructions](http://tools.android.com/tech-docs/new-build-system/migrating-from-eclipse-projects)

**Comment by Lingomat** [comment]
Thanks, I'll give it a go.

About the Android version. Is 4.2.2 our target for the foreseeable future? I'm acquiring a number of phones for fieldwork so this is a key issue. E.g. it's more of a problem if I decide to use refurbished phones with older Androids.

**Comment by stevenbird** [comment]
Yes, 4.2.2 is our target for now. I take it you can build, so I'm closing this.
