### ISSUE TITLE
Public sharing requires permission

### ISSUE THREAD

**Issue by stevenbird** [aikuma/aikuma#438]
Before someone can publicly share a file (causing it to be uploaded to the shared Google drive), they must first agree to the conditions for sharing, cf #437.

Long pressing on an file shows the Aikuma share icon, and if this is selected, and if the user has not yet agreed, they see a toast: `Before sharing, please see the sharing agreement in the settings menu.`

**Comment by floere** [comment]
Could the toast directly show a checkbox and text? This would enable the user to continue with their task. Unless the idea is to also teach a new user about the existence of the settings.

**Comment by lisaslyis** [comment]
@floere Toast can only show a text message, but instead a dialog can be used with a checkbox, button and etc.

**Comment by floere** [comment]
@lisaslyis You're absolutely right. I should have put that differently – it may be a good idea to immediately enable the user to agree.

**Comment by stevenbird** [comment]
+1 let's take the user directly to the sharing agreement; when they agree (or not) and press the back button, they return to the listen activity.

**Comment by stevenbird** [comment]
The toast is no longer necessary.

**Comment by stevenbird** [comment]
Resolved in #486.
