### ISSUE TITLE
Storage capacity

### ISSUE THREAD

**Issue by stevenbird** [aikuma/aikuma#439]
Please work out how many minutes of recorded speech Aikuma stores per megabyte of storage, so we can list this on the [FAQ](http://www.aikuma.org/faq.html) (helping people work out how much storage their phone would need to have).

**Comment by Lingomat** [comment]
16khz 16-bit mono is 32.77 seconds per megabyte. Perhaps you mean gigabyte, in which case it's about 560 minutes per gigabyte.

**Comment by stevenbird** [comment]
Thanks – I confirmed the calculation and updated the [FAQ](http://www.aikuma.org/faq.html).
