### ISSUE TITLE
Speaker file storage

### ISSUE THREAD

**Issue by stevenbird** [aikuma/aikuma#443]
Update File Storage specification with details of the speaker directory.

**Comment by stevenbird** [comment]
This is waiting on #67.

**Comment by Lingomat** [comment]
Not a huge fan of json for the metadata, can we at least output a prettified version for human eyes? I would assume this is just a flag somewhere.

**Comment by Lingomat** [comment]
In fact I'd like to propose that the file store needs an overhaul. It may not be a development priority but we're going to need to think about this when other changes happen like per-source commentary.
 
I've explained more fully here:
https://github.com/aikuma/aikuma/wiki/File-Storage-revision

**Comment by stevenbird** [comment]
This no longer depends on #67, and the specification has been updated.

**Comment by stevenbird** [comment]
@Lingomat the question of storage format needs to be taken up separately.
