### ISSUE TITLE
Aikuma in China

### ISSUE THREAD

**Issue by stevenbird** [aikuma/aikuma#444]
Since Google services are blocked in China, we need to identify an [alternative to Google Play](https://www.techinasia.com/10-android-app-stores-china-2014-edition/), and a work-around for sign-in. @Lingomat do you have any advice?

**Comment by Lingomat** [comment]
There's two issues here, first being distribution of Aikuma. This can be addressed by using third party app stores. 360 assistant, Tencent's one (forget the name), Baidu's and MIUI's are the top ones.  I would say our target audience is probably okay with side-loading an APK too though, right? (I think there's a decent argument for just putting the APK on Aikuma.org too - anyone that does serious work with Aikuma would probably be nervous about automatic updates, I know I am :)

There is marketing value in being on those stores for the vast application of minority languages in China but it seems a concern that's a little distant, to me.

As for the lack of Google services, that's more difficult. Unless we go implement an entirely new cloud platform that exists in China, it strikes me that Aikuma users will need to connect their phones to a VPN service. It strikes me that there's not much of a market for putting an app on Chinese app stores that then needs a VPN to deliver what it says it does. 

So, it is possible to use Aikuma in China but it's marred by a level of inconvenience that probably doesn't make it worth placing on Chinese app stores for a general audience.

None of this applies in Taiwan (the world's 5th largest revenue market for Google Play).

**Comment by stevenbird** [comment]
Thanks @Lingomat.

I propose:
* If the user signed in to their google account outside China, they could still use Aikuma offline, and select this account, and create recordings.
* If the user has a fresh install of Aikuma and never signed in outside China, they can enter their email address (twice, since we'll have no way to change this later). We will use this email address for file ids. This might be a Google account, but we won't know at this point.
* For local sync, they can use p2p-wifi
* Private and public sharing depend on Google Drive, and they can connect to this only via VPN (e.g. [Astrill](https://www.astrill.com/)) or via normal network access outside China.

**Comment by Lingomat** [comment]
Sounds good to me! 

What prompted this? There's someone who wants to work in China?

**Comment by stevenbird** [comment]
@lingomat, that's right.

**Comment by stevenbird** [comment]
Superseded by #448 and #449.
