### ISSUE TITLE
Metadata fields

### ISSUE THREAD

**Issue by Lingomat** [aikuma/aikuma#446]
In order to curate data from Aikuma, we need appropriate metadata. Some of this data relates to sessions, or actual recording activities, and overlaps with tags default tags #442 . Other fields are project based and relate to access. 

Therefore there's a mix of metadata, some of which falls within Aikuma's remit and some which may be better handled on the cloud platform. Compiling a list of essential metadata will shed some light on this.

A Wiki page for the fields has been created here:
https://github.com/aikuma/aikuma/wiki/Metadata-fields

**Comment by Lingomat** [comment]
We have ascertained that project level metadata is out of scope of Aikuma. Furthermore Aikuma leans on recording of file-level commentary as metadata. Easily understood metadata fields are represented in Aikuma's tags system.

A richer metadata record, such as for linguists, will happen outside of Aikuma. However we need to be able to associate Aikuma primary recordings with these records, e.g. SayMore's ID or a simple row handle in an Excel and so on.

**Comment by Lingomat** [comment]
I suspect this is becoming redundant with plans for export to SayMore. I'm not sure I like #447 either.

**Comment by stevenbird** [comment]
I agree @lingomat. We've agreed that the file-level metadata is appropriate, and that the project level metadata is out of scope.
