### ISSUE TITLE
Display ID field of from primary recording

### ISSUE THREAD

**Issue by Lingomat** [aikuma/aikuma#447]
Create a way to display a four character ID (most significant characters from uuid?) for each primary recording. The purpose of this is so that an owner/operator can record detailed metadata outside of Aikuma and have this associated with the Aikuma sessions.

Consider inserting a field such as "Handle: xpek" on the primary recording view. 

I can't think of why we would need to do this on secondary recordings?

**Comment by stevenbird** [comment]
This is an additional requirement for #414.
