### ISSUE TITLE
Distribute APK file via aikuma.org

### ISSUE THREAD

**Issue by stevenbird** [aikuma/aikuma#448]
Push the current aikuma.apk file to github, enabling it to be linked from aikuma.org, so that people can install the apk directly (cf #444).

**Comment by cesine** [comment]
push it in a separate release branch right, so it wont bloat the .git with binary files...

**Comment by stevenbird** [comment]
+1

**Comment by floere** [comment]
https://help.github.com/articles/distributing-large-binaries/

Especially the tip at the bottom linking to Git LFS is interesting.

**Comment by stevenbird** [comment]
The development APK file is now available at http://www.aikuma.org/development.html. We will post the stable APK as well.
