### ISSUE TITLE
To name derived recordings, or not

### ISSUE THREAD

**Issue by Lingomat** [aikuma/aikuma#457]
Previous Aikuma behavior had the user type a name for a respeaking event. This is no longer in Aikuma. As a result, Aikuma's JSON metadata has blank 'name' fields for these recordings:

* name : description of the file (String)

I'm not convinced we need a name. I'm not fond of resorting to an input method on Android, it's unwieldy. We know the type of aligned commentary now and we have plans to use tags to indicate the type of a per-file commentary, correct?

So has the name been deprecated?

**Comment by lisaslyis** [comment]
@Lingomat Name field is now only used in a source recording file. For derivative recording files, name fields is just blank(an empty string) as you said.

**Comment by Lingomat** [comment]
Roger that.
