### ISSUE TITLE
No way to confirm with optional comment

### ISSUE THREAD

**Issue by Lingomat** [aikuma/aikuma#470]
We may type an optional comment for recordings and for new users. However the text input is a large text widget. With the present settings the keyboard will block the tick box to confirm. A workaround is to click back onto the name, this will allow the keyboard to present a finish or next key which will proceed.

This problem can be fixed in the activities manifest. 

```
<activity android:name=".YourActivity" android:windowSoftInputMode="adjustResize"/>  
```

This will resize the screen based on the onscreen keyboard. The tick box should then relocate to above the keyboard. 

Further details:
http://developer.android.com/guide/topics/manifest/activity-element.html

**Comment by stevenbird** [comment]
Thanks for the suggestion. We should probably do this for other screens as well.

**Comment by stevenbird** [comment]
NB you can confirm, but you have to press the back button to dismiss the keyboard.

**Comment by lisaslyis** [comment]
@Lingomat The okButton(with green tick icon) can go upward with the keyboard. But will it make enough space for comments field? because the comments field can have multilnes

**Comment by Lingomat** [comment]
Yes. I don't envisage typing out lines on a phone. I would strongly prefer that people provide descriptions in commentary files.

Also, the phones I'm using are *massive* :)

**Comment by lisaslyis** [comment]
I see. Then, I'll make okButton be always shown with the keyboard. But In
that case, I'm not sure about the use case of comments fields because its
use case seems to be replaced by commentary files.

**Comment by Lingomat** [comment]
Neither am I actually. I could see typing something fairly short in there. On the other hand, my usage doesn't doesn't define Aikuma's features.

**Comment by stevenbird** [comment]
It's often useful to have a place to enter some written comments about a
speaker or a recording.

**Comment by Lingomat** [comment]
For me, yes. I'm confident on a mobile keyboard. I'm less convinced in unsupervised settings. In scenarios where I am operating the phone, it's more profitable for me to type fuller metadata outside of Aikuma. E.g. SayMore.
