### ISSUE TITLE
Inconsistency of back button (add confirm on main activity)

### ISSUE THREAD

**Issue by Lingomat** [aikuma/aikuma#474]
Pressing the back button should be context sensitive. If one is viewing an item, it should always return to the main screen. Sometimes this does not occur.

The user may be transported back to a respeaking activity. Leaving this activity will generate warnings about data being discarded. This may be distressing for the user since they think they are about to lose the recording they made.

I also propose that a confirmation message appears if the user hits 'back' on the main activity and they do not intend to exit the application (which is almost always the case). I've seen this approach in other apps to good effect.

**Comment by lisaslyis** [comment]
@Lingomat Could you give me some more details? For example,
1. What is the context of viewing an item? when should it return to the main screen?
2. What is the case of being transported back to a respeaking activity? Do you mean when hitting a back button on the respeaking confirmation page?

**Comment by Lingomat** [comment]
It should always return to the main screen when hitting back.  I'm pretty sure I was on the item view page when I hit back and ended up in a respeaking activity. Is this possible? Because I swear it happened twice this morning but I can't make it happen again.

**Comment by lisaslyis** [comment]
If you mean the respeaking activity page as the one with play and record buttons, then no, you should not be allowed to go to the respeaking activity page by hitting a back button in the item view page.

**Comment by Lingomat** [comment]
Okay. Let's close until if and when I can reproduce it!
