### ISSUE TITLE
replace "sign out:" with "sign out" 

### ISSUE THREAD

**Issue by HedvigS** [aikuma/aikuma#476]
There's a superfluous colon. Sorry for being nitpicky, I was just first thinking it had a menu but it doesn't. Also, I haven't tried exhaustively, but I can't so far understand how to sign in with a different account.

**Comment by stevenbird** [comment]
Thanks @hedvigS. Yes, we need to remove the colon.

To sign in with a different account, you first need to have added that account to the phone (via the Settings -> Accounts -> Google menu).

**Comment by stevenbird** [comment]
Thanks @hedvigS. Yes, we need to remove the colon.

To sign in with a different account, you first need to have added that account to the phone (via the Settings -> Accounts -> Google menu).

**Comment by stevenbird** [comment]
Resolved in #486.
