### ISSUE TITLE
GoogleDriveStorage: Add option to make copy shared files

### ISSUE THREAD

**Issue by hleeldc** [aikuma/aikuma#498]
By default shared files are "linked". But, for central drive, shared files should be "copied". Provide an option for this in the constructor of GoogleDriveStorage.

**Comment by stevenbird** [comment]
@lisaslyis is this still current?

**Comment by lisaslyis** [comment]
@stevenbird Now, All shared aikuma files, which starts with v0x/, are copied to central folder and moved to central trash folder.
