### ISSUE TITLE
Flatten file structure

### ISSUE THREAD

**Issue by stevenbird** [aikuma/aikuma#514]
The decision to create extra levels of nesting for accounts, e.g. `/u/us/user@gmail.com`, was based on a wrong assumption that cloud storage was akin to a unix filesystem. There will usually not be very many userids on a single phone, so this structure is unmotivated. Let's drop it, and adopt a flat structure for `/v03`.

Cf https://github.com/aikuma/aikuma/wiki/File-Storage

**Comment by Lingomat** [comment]
\o/

**Comment by stevenbird** [comment]
Resolved by #542
