### ISSUE TITLE
Data format (e.g. for mapping file)

### ISSUE THREAD

**Issue by floere** [aikuma/aikuma#63]
As the next version is 1.0, we should stabilise the data formats, with the goal of readability in mind:

* Mapping file, was "start_a,end_a:start_b,end_b" – should be "start_a,end_a,start_b,end_b". This turns the mapping file into an actual CSV file and makes it possible to use standard CSV readers in all (computer) languages.
* Other examples which could be improved?

**Comment by stevenbird** [comment]
An alternative is to use JSON, for extensibility, and consistency with our use of our metadata format, e.g.

```
{"mapping": [
   {"source": [1.234,2.345], "target": [3.456,4.567]}
   {"source": [...], "target": [...]}
   {...}
   ]
}
```
